echo "	A	B"
echo "L'ensemble {1, 2, 3} est inclus dans N"
echo "Elle demanda d'une voix *forte* : \"Qui est-ce ?\"" 
echo "\$HOME = \${HOME} = $HOME"
echo "19 * 216 = $((33*17))"
echo "Ajoutez un peu d'huile d'olive, d'humeur joyeuse, d'hulus, et remuez bien !"