CC=gcc
CFLAGS=-Wall -std=c11
CPPFLAGS=-D_POSIX_C_SOURCE=200112L -DNDEBUG
LDLIBS=-lrt -pthread

ALL =   ecrivain_nomme lecteur_nomme

all : $(ALL)
prefix_slash.o: prefix_slash.c prefix_slash.h

lecteur_nomme.o: lecteur_nomme.c panic.h prefix_slash.h
lecteur_nomme: lecteur_nomme.o prefix_slash.o


ecrivain_nomme.o: ecrivain_nomme.c panic.h prefix_slash.h
ecrivain_nomme: ecrivain_nomme.o prefix_slash.o


clean:
	rm -rf *~
cleanall:
	rm -rf *~ $(ALL) *.o
